# Generated by Django 2.0.6 on 2018-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupIndex', models.AutoField(db_column='groupIndex', primary_key=True, serialize=False)),
                ('groupName', models.CharField(db_column='groupName', max_length=50, unique=True)),
                ('essIndex24', models.CharField(db_column='essIndex24', max_length=1024)),
                ('essIndex5', models.CharField(db_column='essIndex5', max_length=1024)),
                ('apType', models.PositiveIntegerField(db_column='apType')),
                ('active', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'tb_group',
                'managed': False,
            },
        ),
    ]
